=== AndrijaFE/Provera-Znanja/magacin.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.w3schools.com/" elementFormDefault="qualified" targetNamespace="http://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name='Magacin'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='Artikal' minOccurs='1' maxOccurs='unbounded'>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name='Naziv'>
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base='xs:NazivRestrikcija'>
                                            <xs:attribute name='sifra' use='required'/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name='DatumIzrade'>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name='Dan'>
                                            <xs:simpleType>
                                                <xs:restriction base='xs:positiveInteger'>
                                                    <xs:minInclusive value="1" />
                                                    <xs:maxInclusive value="31" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name='Mesec'>
                                            <xs:simpleType>
                                                <xs:restriction base='xs:positiveInteger'>
                                                    <xs:minInclusive value="1" />
                                                    <xs:maxInclusive value="12" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name='Godina' type='xs:positiveInteger'/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name='Cena'>
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base='TypeCena'>
                                            <xs:attribute name='tip' use='required'>
                                                <xs:simpleType>
                                                    <xs:restriction base='xs:NMTOKEN'>
                                                        <xs:enumeration value='dinari'/>
                                                        <xs:enumeration value='euro'/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>  
                                       </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name='KompanijaProdavca'>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name='ImeKompanija' type='xs:string'/>
                                        <xs:element name='Adresa' type='xs:string' minOccurs='1' maxOccurs='unbounded'/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name='EmailProdavca' maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base='OgranicenjeEmail'>
                                            <xs:attribute name='tip' use='required'>
                                                <xs:simpleType>
                                                    <xs:restriction base='xs:NMTOKEN'>
                                                        <xs:enumeration value='privatni'/>
                                                        <xs:enumeration value='sluzbeni'/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name='OgranicenjeEmail'>
        <xs:restriction base='xs:string'>
            <xs:pattern value="([0-9]{1}[a-z][A-Z]{1}){0,20}@\c{4,8}.com"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TypeCena">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>
    <xs:simpleType name="NazivRestrikcija">
        <xs:restriction base="xs:string">
            <xs:minLength value="3" />
            <xs:maxLength value="30" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AndrijaFE/Provera-Znanja/magacin.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE Magacin SYSTEM "magacin.dtd">

<Magacin xmlns="http://www.w3schools.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com magacin.xsd">
  <Artikal>
    <Naziv sifra="">Knjiga</Naziv>
    <DatumIzrade>
      <Dan>5</Dan>
      <Mesec>8</Mesec>
      <Godina>2020</Godina>
    </DatumIzrade>
    <Cena tip="dinari">800</cena>
    <KompanijaProdavca>
      <ImeKompanija>Laguna</ImeKompanija>
      <Adresa>Vojvode stepe</Adresa>
      <Adresa>Vojvode stepe 1234</Adresa>
    </KompanijaProdavca>
    <EmailProdavca tip="sluzbeni">nekiemail123@nesto.com</EmailProdavca>
    <EmailProdavca tip="privatni">nekiemail@nesto.com</EmailProdavca>
  </Artikal>

  <Artikal>
    <Naziv sifra="">Sok</Naziv>
    <DatumIzrade>
      <Dan>9</Dan>
      <Mesec>10</Mesec>
      <Godina>2018</Godina>
    </DatumIzrade>
    <Cena tip="euro">5</cena>
    <KompanijaProdavca>
      <ImeKompanija>Koka kola</ImeKompanija>
      <Adresa>KokaKola 1234</Adresa>
      <Adresa>KokaKola</Adresa>
    </KompanijaProdavca>
    <EmailProdavca tip="privatni">kokakola@nesto.com</EmailProdavca>
    <EmailProdavca tip="sluzbeni">kokakola1234@nesto.com</EmailProdavca>
  </Artikal>

</Magacin>
